AvoidPunctuation:
  Enabled: true
InvalidFileName:
  Enabled: true
MissingFeatureName:
  Enabled: true
MissingScenarioName:
  Enabled: true
MissingFeatureDescription:
  Enabled: true
MissingScenarioAction:
  Enabled: true
MissingScenarioResult:
  Enabled: true
