AvoidPunctuation:
  Enabled: true
InvalidFileName:
  Enabled: true
MissingFeatureName:
  Enabled: true
MissingScenarioName:
  Enabled: true
MissingFeatureDescription:
  Enabled: true
MissingScenarioAction:
  Enabled: true
MissingScenarioResult:
  Enabled: true
DuplicateScenarioNames:
  Enabled: true
OverlyLongScenario:
  Enabled: true
OverlyLongSteps:
  Enabled: true
TooManyTags:
  Enabled: true
