AvoidPunctuation:
  Enabled: true
AvoidDuplicateScenarioNames:
  Enabled: true
AvoidNonContextBackgrounds:
  Enabled: true
AvoidSingleScenarioBackgrounds:
  Enabled: true
AvoidTooManyTags:
  Enabled: true
InvalidFileName:
  Enabled: true
MissingFeatureName:
  Enabled: true
MissingScenarioName:
  Enabled: true
MissingExampleName:
  Enabled: true
MissingFeatureDescription:
  Enabled: true
MissingScenarioAction:
  Enabled: true
MissingScenarioResult:
  Enabled: true
OverlyLongScenario:
  Enabled: true
OverlyLongSteps:
  Enabled: true
OverlyDetailedScenario:
  Enabled: true
