AvoidPunctuation:
  Enabled: true
AvoidDuplicateScenarioNames:
  Enabled: true
AvoidNonContextBackgrounds:
  Enabled: true
AvoidSingleScenarioBackgrounds:
  Enabled: true
AvoidTooManyScenarioTags:
  Enabled: true
AvoidNonDeclarative:
  Enabled: true
AvoidUnusedVariables:
  Enabled: true
PreferFeatureDescription:
  Enabled: true
PreferSnakeCaseFileName:
  Enabled: true
MissingFeatureName:
  Enabled: true
MissingScenarioName:
  Enabled: true
MissingExampleName:
  Enabled: true
MissingScenarioAction:
  Enabled: true
MissingScenarioResult:
  Enabled: true
MissingVariableName:
  Enabled: true
OverlyLongScenario:
  Enabled: true
OverlyLongStep:
  Enabled: true
OverlyDetailedScenario:
  Enabled: true
